config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :own_posts
  resources :posts do
    
    resources :comments
    member do
      put "like",    to: "posts#upvote"
    end    
  end

scope ":locale", defaults: { locale: I18n.locale } do
  ActiveAdmin.routes(self)
end 

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  root "posts#index"

end

app/controllers/own_posts_controller.rb
class OwnPostsController < ApplicationController
	before_action :find_own_posts, only: [:index ]
	before_action :find_current_post, only: [:show,:destroy]
	def index
		
	end
	def show
		@comments = Comment.where(post: @post)
	end
	def destroy
		if @post.destroy
			redirect_to root_path
		end
	end

		private
			def find_own_posts
				@post = Post.where("user_id = ?", current_user.id).all				
			end
			def find_current_post
				@post = Post.where("user_id = ? AND id =?", current_user.id, params[:id]).first
			end
end

app/helpers/own_posts_helper.rb
module OwnPostsHelper
end

app/views/own_posts/_form.html.haml
= simple_form_for @post, html: {multipart: true} do |f|
  - if @post.errors.any?
    #errors
      %h2
      = pluralize(@post.errors.count, 'error')
      prevented this Post from saving
      %ul
      - @post.errors.full_message.each do |msg|
        %li= msg
  .form-group
    = f.input :image, input_html: {class: 'form-controller'}
  .form-group
    = f.input :title, input_html: {class: 'form-controller'}
  .form-group
    = f.input :description, input_html: {class: 'form-controller'}
  = f.button :submit, class: "btn btn-primary"

app/views/own_posts/index.html.haml
#posts.transitions-enabled
  -@post.each do |item|
    .box.panel.panel-default
      = link_to (image_tag item.image.url), item
      %h2= link_to item.title, own_post_path(item)
      .row.user
        .col-md.my-post-status
          Status
          -if item.state == "approved"
            %span.approve
              =item.state
          -else
            %span.not_approve
              =item.state

app/views/own_posts/show.html.haml
#post_show.row
  .col-md-6.col-offset-2
    .panel.panel-default
      
      .panel-heading.post_image
        = image_tag @post.image.url
      
      .panel-body
        %h1=@post.title
        %p=@post.description
        %p=#raw(@post.description)
              
        
      .panel-footer
        .row
          .col-md-6
            %p.user
              Submited by
              =@post.user.email
          .col-md-6
            .btn-group.pull-right
              -if @post.approved? 
                = link_to like_post_path(@post), method: :put, class: "btn btn-default" do 
                  %span.glyphicon.glyphicon-heart
                  = @post.get_upvotes.size 
              - if user_signed_in? && current_user == @post.user
                =link_to 'Back', root_path, class: "btn btn-default"
                =link_to 'Edit', edit_post_path, class: "btn btn-default" if @post.approved?
                =link_to 'Delete', post_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"
          .col-md-6#comments
          -if @post.approved? 

            %h2.comment_count= pluralize(@post.comments.count, "Comment")
            -@comments.each do |comment|
              .comment
                %p.username= comment.user.email
                %p.comment_content= comment.content
                - if user_signed_in? && current_user.id == 1
                  =link_to 'Delete', [@post, comment], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"
            =render 'comments/form'